library(limma)
library(illuminaio)
setwd("/home/intsira/Documents/BioInfo-Clustering/BioInfo")
idatFiles= file.choose()
bgxfile=file.choose()
obj<-read.idat(idatFiles, bgxfile, dateinfo=TRUE,annotation = "Symbol",tolerance=0L, verbose = TRUE)
View(obj$targets)
View(obj$E)
View(obj$genes)
View(obj$other$NumBeads)
View(obj$other$STDEV)          
d = readIDAT(idatFiles)
print(d)
